"""New full recovery comparison; dry-run has no credential, file or API effects."""
from __future__ import annotations

import argparse
from copy import deepcopy
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from scripts import run_agent_study_1m as parent
from scripts.agent_study_specs import STUDY_SPEC_PROFILE
from scripts.agent_token_budget import BudgetedProvider, TokenBudget
from scripts.run_agent_comparison import BASELINES, CASES, execute, sha
from iverilog_ai.ai.local_api_profile import read_key_file

CONFIG = ROOT / "spec/agent_recovery_study_1m.json"
PLAN = ROOT / "docs/experiment/agent_recovery_study_plan_2026-10-05.md"
INPUTS = ROOT / ".iverilog-ai/agent-recovery-study-20261005-inputs"
OUTPUT = ROOT / ".iverilog-ai/agent-recovery-study-live-20261005"
STRATEGIES = ("fixed", "random", "protocol_random", "single", "feedback", "no_feedback")
_TRANSPORT = {"endpoint": "https://api.deepseek.com", "model": "deepseek-flash",
              "wire_api": "chat_completions", "thinking_mode": "disabled", "stream": False,
              "timeout_seconds": 60, "automatic_transport_retry": False}
_CYCLES = {"sync_fifo": 16, "uart_tx": 48, "spi_master": 20, "handshake_stage": 8}


def preregister_recovery_study() -> tuple[dict, dict[Path, bytes]]:
    """Reuse public parent registration and generated bytes, never prior run files."""
    config = json.loads(CONFIG.read_text(encoding="utf-8"))
    transport = config.get("transport", {})
    if (config.get("schema") != "agent-recovery-study-per-round-v1"
            or config.get("token_cap") != 1_000_000 or config.get("repeats") != 3
            or config.get("strategies") != list(STRATEGIES)
            or config.get("cycle_budgets") != _CYCLES
            or config.get("max_output_tokens_per_request") != 4096
            or config.get("theoretical_request_cap") != 252
            or transport != _TRANSPORT or type(transport.get("stream")) is not bool
            or type(transport.get("automatic_transport_retry")) is not bool
            or type(transport.get("timeout_seconds")) is not int
            or config.get("parent_config_path") != "spec/agent_study_1m.json"
            or set(config.get("generated_spec_sha256", {})) != set(CASES)):
        raise ValueError("invalid recovery study scope")
    if sha(parent.CONFIG) != config["parent_config_sha256"]:
        raise ValueError("parent configuration drift")
    parent_config = json.loads(parent.CONFIG.read_text(encoding="utf-8"))
    shared = ("token_cap", "max_output_tokens_per_request", "repeats", "strategies", "cycle_budgets")
    if any(config[key] != parent_config[key] for key in shared):
        raise ValueError("parent configuration drift")
    original_reg, parent_generated = parent.preregister_study()
    reg = deepcopy(original_reg)
    if len(reg["rows"]) != 216 or reg["theoretical_requests"] != 252 or reg["independent_holdout"]:
        raise ValueError("parent membership differs from registered comparison")
    if sum(0 if row["strategy"] in BASELINES else 1 if row["strategy"] == "single" else 3
           for row in reg["rows"]) != reg["theoretical_requests"]:
        raise ValueError("parent API allocation differs from registered comparison")
    for strategy in STRATEGIES:
        rows = [row for row in reg["rows"] if row["strategy"] == strategy]
        if (len(rows) != 36 or sum(row["variant"] != "reference" for row in rows) != 24
                or {row["seed"] for row in rows} != {0, 1, 2}
                or any(row["status"] != "not_started" or row["requests"] or row["rounds"]
                       or row["budget_cycles"] != _CYCLES[row["case"]] for row in rows)):
            raise ValueError("parent membership differs from registered comparison")
    if set(parent_generated) != {parent.INPUTS / f"{case}_spec.md" for case in CASES}:
        raise ValueError("parent specification membership drift")
    generated = {}
    spec_hashes = {}
    for case in CASES:
        source = parent.INPUTS / f"{case}_spec.md"
        content = parent_generated[source]
        digest = hashlib.sha256(content).hexdigest()
        if digest != config["generated_spec_sha256"][case]:
            raise ValueError("parent generated specification drift")
        item = reg["protocol_config"]["cases"][case]
        old_path = source.relative_to(ROOT).as_posix()
        if (item["spec_path"] != old_path or reg["code_and_input_sha256"].get(old_path) != digest):
            raise ValueError("parent generated specification binding drift")
        target = INPUTS / f"{case}_spec.md"
        new_path = target.relative_to(ROOT).as_posix()
        reg["code_and_input_sha256"].pop(old_path)
        reg["code_and_input_sha256"][new_path] = digest
        item["spec_path"] = new_path
        generated[target] = content
        spec_hashes[case] = digest
    prior_prompt = config["parent_prompt"]
    current_prompt = {key: reg["prompt_profile"][key]
                      for key in ("agent_prompt_version", "system_prompt_sha256")}
    reg["scope"] = "development_full_bounded_recovery_batch_not_independent_holdout"
    reg["study"] = {
        "name": config["round_name"], "limits": config,
        "primary": "detected defect tasks out of 24 per strategy, including all failures",
        "secondary": ["per_repeat", "unique_union", "schema_acceptance", "format_recovery",
                      "retained_rejections", "requests", "tokens", "cycles", "elapsed"],
        "order": original_reg["study"]["order"],
        "prompt_intervention": STUDY_SPEC_PROFILE,
        "specification_bytes_identical_to_parent": spec_hashes,
        "parent_public_config_sha256": config["parent_config_sha256"],
        "parent_source_commit": config["parent_source_commit"],
        "change_scope": "bounded ordinary schema recovery and malformed-response retention; no wider action schema or oracle changes",
        "prompt_change_disclosure": {"parent": prior_prompt, "current": current_prompt,
                                     "changed": current_prompt != prior_prompt,
                                     "interpretation": "If the system prompt changes, recovery and prompting change together; not a single-factor causal claim."},
        "independent_model_rng": False, "history_not_charged_to_this_batch": True,
        "prior_results_never_replaced": True,
        "feedback_caveat": "no_feedback hides ordinary-format diagnostics and plan_error as well as DUT observations and coverage; recovery may request again without rejection details; executor-driven early stopping remains",
        "comparison_caveat": "same public development modules and defects; no blind independent holdout or statistical significance claim",
    }
    reg["protocol"]["no_feedback"] = reg["study"]["feedback_caveat"]
    reg["prompt_profile"].update(study=reg["study"], max_rounds=3)
    reg["prompt_profile_sha256"] = hashlib.sha256(json.dumps(reg["prompt_profile"], sort_keys=True).encode()).hexdigest()
    for path in (CONFIG, PLAN, Path(__file__).resolve(), parent.CONFIG,
                 ROOT / "scripts/run_agent_study_1m.py", ROOT / "scripts/agent_study_specs.py",
                 ROOT / "scripts/agent_token_budget.py", ROOT / "tests/core/test_agent_recovery_study.py"):
        reg["code_and_input_sha256"][path.relative_to(ROOT).as_posix()] = sha(path)
    return reg, generated


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--api-key-file", type=Path)
    args = parser.parse_args(argv)
    try:
        reg, generated = preregister_recovery_study()
        config = reg["study"]["limits"]
        print(json.dumps({"mode": "execute" if args.execute else "dry_run", "rows": len(reg["rows"]),
                          "theoretical_requests": reg["theoretical_requests"], "round_token_cap": config["token_cap"],
                          "system_prompt_changed": reg["study"]["prompt_change_disclosure"]["changed"]}))
        if not args.execute:
            return 0
        if (INPUTS.exists() or INPUTS.is_symlink() or OUTPUT.exists() or OUTPUT.is_symlink()
                or not args.api_key_file):
            raise ValueError("new inputs/output and credential file required")
        key = read_key_file(args.api_key_file)
        INPUTS.mkdir(parents=True, exist_ok=False)
        for path, content in generated.items():
            with path.open("xb") as stream:
                stream.write(content)
        budget = TokenBudget(config["token_cap"], OUTPUT / "token_budget.json")
        transport = config["transport"]
        def factory(count):
            return BudgetedProvider(token_budget=budget, endpoint=transport["endpoint"], model=transport["model"],
                api_key=key, allow_network=True, store=False, reasoning_effort=None,
                thinking_mode=transport["thinking_mode"], timeout=transport["timeout_seconds"],
                stream=transport["stream"], request_limit=count, wire_api=transport["wire_api"],
                max_output_tokens=config["max_output_tokens_per_request"], force_output_limit=True)
        try:
            execute(reg, OUTPUT, endpoint=transport["endpoint"], model=transport["model"], key=key,
                request_cap=reg["theoretical_requests"], max_output_tokens=config["max_output_tokens_per_request"],
                wire_api=transport["wire_api"], thinking_mode=transport["thinking_mode"],
                iverilog="D:/iverilog/bin/iverilog.exe", vvp="D:/iverilog/bin/vvp.exe",
                provider_factory=factory, provider_factory_record_kind="api_and_local_simulation")
        finally:
            if OUTPUT.exists():
                budget.save()
        return 0
    except Exception as exc:
        print(f"Recovery study failed: {type(exc).__name__}")
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
